### PR TITLE
fix: error message on PatientRegistration failure

### LINKED ISSUE #140: patient registration interceptor does not work on dotbase-demo

### PR DESCRIPTION
**Pull request by rti**
closes #140
The actual error was caused by the FHIR server trying to recreate patients on keycloak which were already created. So the behavior is as expected and should not be changed. This change improves the error message in order to guide our future selves.

### CODE REVIEW

File: src/main/java/ca/uhn/fhir/jpa/starter/dotbase/services/PatientRegistration.java [hunk 1]
```diff
@@ -15,7 +14,7 @@
 
 @Service
 public class PatientRegistration {
-  private static final org.slf4j.Logger ourLog = org.slf4j.LoggerFactory.getLogger(PatientRegistration.class);
+  // private static final org.slf4j.Logger ourLog = org.slf4j.LoggerFactory.getLogger(PatientRegistration.class);
```
Comment (friedow) [inline src/main/java/ca/uhn/fhir/jpa/starter/dotbase/services/PatientRegistration.java:17]: There is some dead comment left ;)

**Review by friedow — CHANGES_REQUESTED** [review]

**Review by friedow — APPROVED** [review]

**Review by andreakreichgauer — APPROVED** [review]
